package com.brulser.graduationproject.javabean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.brulser.graduationproject.javabean.Newitem;

import com.brulser.graduationproject.javabean.NewitemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig newitemDaoConfig;

    private final NewitemDao newitemDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        newitemDaoConfig = daoConfigMap.get(NewitemDao.class).clone();
        newitemDaoConfig.initIdentityScope(type);

        newitemDao = new NewitemDao(newitemDaoConfig, this);

        registerDao(Newitem.class, newitemDao);
    }
    
    public void clear() {
        newitemDaoConfig.clearIdentityScope();
    }

    public NewitemDao getNewitemDao() {
        return newitemDao;
    }

}
